### ISSUE TITLE
Room Persistent

### ISSUE THREAD

**Issue by ranggazay** [SamYStudiO/Beaver#1]
How to implement Room Persistence Library to this template ?

**Comment by SamYStudiO** [comment]
Hi and sorry for late answer.
I've just added Room database to project. Let me know if you have any additional questions.

**Comment by ranggazay** [comment]
Great,,, you're the best,,,

**Comment by ranggazay** [comment]
Hello, I'm sorry I asked a lot, I don't know where I should ask about this, so far I've been using a template project for about a year, there are a few that I want to ask:
1. how to add parameters in ApiInterface, say I want to add parameters for pagination or for search filters
2. How to develop Offline-First Architecture, so that data can be retrieved from the database (room), if data fails to be retrieved from the API.
3. how to make synchronization background function in data in local (room) to API, if there is newer data in local data
actually there are still many that I want to ask, but I think that's just what I thought was a high priority
Once again, I'm sorry I asked a lot of questions and thank you for taking the time to answer my question
